title: Yunwen Liu's homepage
theme: minima
minima:
  social:
    google_scholar: https://scholar.google.com/citations?hl=en&user=fbnd6LMAAAAJ
    linkedin: https://www.linkedin.com/in/yunwen-liu-a631bb122/
    github: https://github.com/YunwenL
