title: Yunwen Liu's homepage
theme: minima
minima:
  social_links:
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?hl=en&user=fbnd6LMAAAAJ" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yunwen-liu-a631bb122/" }
    - { platform: github,  user_url: "https://github.com/YunwenL" }
